trigger:
- main

stages:
  - stage: BuildandPUSHimagetoACR
    jobs:
      - job: Build_Push
        pool: 
         name: userpool
         demands:
          - Agent.Name -equals ajdevvm
        steps:
          - task: Docker@2
            inputs:
              containerRegistry: 'ganjiacr'
              repository: 'ajdevops/app1'
              command: 'buildAndPush'
              Dockerfile: '**/dockerfile'
              tags: '$(Build.SourceVersion)'
          - task: CopyFiles@2
            inputs:
              SourceFolder: '$(System.DefaultWorkingDirectory)/manifests'
              Contents: '**'
              TargetFolder: '$(Build.ArtifactStagingDirectory)'
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'manifests'
              publishLocation: 'Container'
  - stage: Deploy_to_AKS
    dependsOn: BuildandPUSHimagetoACR
    jobs:
      - deployment: aksdeploy
        displayName: aksdeploy
        environment: defaultenv.default
        pool: 
         name: userpool
         demands:
          - Agent.Name -equals ajdevvm
        workspace:
          clean: all
        strategy:
          runOnce:
            deploy:
              steps:
                - task: DownloadPipelineArtifact@2
                  inputs:
                    buildType: 'current'
                    artifactName: 'manifests'
                    targetPath: '$(System.ArtifactsDirectory)/manifests'
                - task: KubernetesManifest@0
                  inputs:
                    action: 'createSecret'
                    #kubernetesServiceConnection: 'devenv-aksdevops-dev-1660734623942'
                    namespace: 'dsfault'
                    secretType: 'dockerRegistry'
                    secretName: 'ganjacr-azdevops-secret'
                    dockerRegistryEndpoint: 'ganjiacr'
                - task: KubernetesManifest@0
                  inputs:
                    action: 'deploy'
                    #kubernetesServiceConnection: 'devenv-aksdevops-dev-1660734623942'
                    namespace: 'dsfault'
                    manifests: |
                      $(System.ArtifactsDirectory)/manifests/deployment.yaml
                      $(System.ArtifactsDirectory)/manifests/services.yaml
                    containers: 'ganjiacr.azurecr.io/ajdevops/app1:$(Build.SourceVersion)'
                    imagePullSecrets: 'ganjacr-azdevops-secret'
        